name: macOS PyInstaller Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install build deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller reportlab music21 pillow

      - name: Build with PyInstaller
        run: |
          # debug: show the command that will run
          echo "PYINSTALLER CMD:"
          echo pyinstaller --noconfirm --clean --onefile TEST.py --add-data 'assets/title.png:.' --add-data 'assets/ico.png:.' --add-data 'assets/fonts:assets/fonts'
          # run pyinstaller with single-quoted --add-data args to avoid literal double-quote injection
          pyinstaller --noconfirm --clean --onefile TEST.py --add-data 'assets/title.png:.' --add-data 'assets/ico.png:.' --add-data 'assets/fonts:assets/fonts'

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: DriveAnalyzer-macos
          path: dist/

