name: macOS PyInstaller Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install build deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller reportlab music21 pillow

      - name: Build with PyInstaller
        run: |
          # adjust --add-data if your resources live elsewhere
          pyinstaller --noconfirm --clean --onefile TEST.py

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: DriveAnalyzer-macos
          path: dist/
