name: macOS PyInstaller Build (universal)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-matrix:
    name: Build (${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ 'arm64', 'x86_64' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            arch -x86_64 python3 -m pip install --upgrade pip
            arch -x86_64 python3 -m pip install pyinstaller reportlab music21 pillow
          else
            python3 -m pip install --upgrade pip
            python3 -m pip install pyinstaller reportlab music21 pillow
          fi

      - name: Build with PyInstaller
        run: |
          set -eux
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            echo "Building x86_64 with Rosetta (arch -x86_64)"
            arch -x86_64 pyinstaller --noconfirm --clean --onefile TEST.py --add-data assets/title.png:. --add-data assets/ico.png:. --add-data assets/fonts:assets/fonts
            mv dist/TEST dist/TEST-x86_64 || true
          else
            echo "Building arm64"
            pyinstaller --noconfirm --clean --onefile TEST.py --add-data assets/title.png:. --add-data assets/ico.png:. --add-data assets/fonts:assets/fonts
            mv dist/TEST dist/TEST-arm64 || true
          fi

      - name: Upload arch artifact
        uses: actions/upload-artifact@v4
        with:
          name: driveanalyzer-${{ matrix.arch }}
          path: dist/

  make-universal:
    name: Create universal binary
    needs: build-matrix
    runs-on: macos-latest
    steps:
      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: driveanalyzer-arm64
          path: ./artifacts/arm64

      - name: Download x86_64 artifact
        uses: actions/download-artifact@v4
        with:
          name: driveanalyzer-x86_64
          path: ./artifacts/x86_64
        continue-on-error: true

      - name: Prepare files
        run: |
          set -eux
          ARM_BIN=$(ls ./artifacts/arm64/dist/* | grep -v '\.DS_Store' | head -n1 || true)
          X86_BIN=$(ls ./artifacts/x86_64/dist/* | grep -v '\.DS_Store' | head -n1 || true)
          echo "ARM_BIN=${ARM_BIN}"
          echo "X86_BIN=${X86_BIN}"
          mkdir -p out
          if [ -f "$ARM_BIN" ]; then cp "$ARM_BIN" out/TEST-arm64; fi
          if [ -f "$X86_BIN" ]; then cp "$X86_BIN" out/TEST-x86_64; fi

      - name: Create universal with lipo (if both present)
        run: |
          set -eux
          if [ -f out/TEST-arm64 ] && [ -f out/TEST-x86_64 ]; then
            lipo -create out/TEST-x86_64 out/TEST-arm64 -output out/TEST-universal
            chmod +x out/TEST-universal
            echo "Created universal binary out/TEST-universal"
          elif [ -f out/TEST-arm64 ]; then
            cp out/TEST-arm64 out/TEST-universal
            chmod +x out/TEST-universal
            echo "Only arm64 available; using arm64 binary"
          elif [ -f out/TEST-x86_64 ]; then
            cp out/TEST-x86_64 out/TEST-universal
            chmod +x out/TEST-universal
            echo "Only x86_64 available; using x86_64 binary"
          else
            echo "No built binary found" >&2
            exit 1
          fi

      - name: Package universal artifact
        run: |
          mkdir -p out/dist
          cp out/TEST-universal out/dist/TEST
          zip -r driveanalyzer-macos-universal.zip out/dist

      - name: Upload universal artifact
        uses: actions/upload-artifact@v4
        with:
          name: DriveAnalyzer-macos-universal
          path: driveanalyzer-macos-universal.zip
